### ISSUE TITLE
 build-system :Lock on auth screen

### ISSUE THREAD

**Issue by ronan22** [AlmaLinux/build-system#10]
After deploying the  docker-compose of web-server, I open the URL:

http://0.0.0.0:8080/auth/login

1) First error
https://github.com/login/oauth/authorize?client_id=undefined&scope=read%3Auser%2Cuser%3Aemail%2Cread%3Aorg

Even if I define "GITHUB_CLIENT=XXXXXXXXXXXXX" in my vars.env file I've got
client_id=undefined
So the URL is wrong.

2) second error
After bypass the First error After open the link:
http://0.0.0.0:8080/auth/login
I'm redirected to the same page:
http://0.0.0.0:8080/auth/login

Same issue on the upstream URL:
https://build.almalinux.org

**Comment by Korulag** [comment]
Hi @ronan22. Thanks for the issue! The reason of it may be in a fact that as of now we expect people to be in AlmaLinux organization for successful login. That might be the main reason why you cannot login. We will be changing this behavior, but I cannot provide you an ETA for the fix. As a workaround, you can modify `github_login` function in `alws/crud.py` file to make it work with your github client ID.

**Comment by ronan22** [comment]
OK, thanks
