### ISSUE TITLE
Fix multilib in builds

### ISSUE THREAD

**Issue by forbiddenpotato** [AlmaLinux/build-system#113]
see https://build.almalinux.org/build/6996 for example

**Comment by anfimovdm** [comment]
This change should probably help
https://github.com/AlmaLinux/albs-web-server/blob/albs-699-2/alws/utils/multilib.py#L137

**Comment by soksanichenko** [comment]
Results
![image](https://github.com/AlmaLinux/build-system/assets/50624082/6024779a-ceee-4b05-b229-68e8009fdf9e)
![image](https://github.com/AlmaLinux/build-system/assets/50624082/5800b996-c66b-4b6c-9e01-8feb8cbc677a)
