### ISSUE TITLE
Create library to work with GitHub (for use on build node, releaser, git updater, test node)

### ISSUE THREAD

**Issue by forbiddenpotato** [AlmaLinux/build-system#126]
Action:
* create issue from new data (git updater)
* change status (build node, test node, releaser)
* add comment (build node, test node, releaser)
* close issue? (releaser or external script?)

**Comment by anfimovdm** [comment]
There is no need to create our own library because we can just use [the `pygithub` library](https://github.com/PyGithub/PyGithub), which requires `Python>=3.7`

Here are examples of how to work with Github issues:
https://pygithub.readthedocs.io/en/stable/examples/Issue.html
