### ISSUE TITLE
Incorrect permission with albs-frontend node_modules

### ISSUE THREAD

**Issue by linlinger** [AlmaLinux/build-system#131]
When I follow the instruction at https://github.com/AlmaLinux/albs-deploy.  I found that I could not access the frontend page . The page is showing "Cannot GET /". and I looked into the request, it's a 404 response. 
![image](https://github.com/AlmaLinux/build-system/assets/32541118/af2c37cb-f53b-4624-a6a0-fa9a970f9e40)

And with the help of other  people. I checked the container log. Below is a part of the logs
`> albs-frontend@0.0.1 dev
> quasar dev

 Dev mode.......... spa
 Pkg quasar........ v2.12.3
 Pkg @quasar/app... v3.3.3
 Pkg webpack....... v5
 Debugging......... enabled

 Configured browser support (>= 86.81% of global marketshare):
 · Chrome for Android >= 115
 · Firefox for Android >= 115
 · Android >= 115
 · Chrome >= 106
 · Edge >= 112
 · Firefox >= 106
 · iOS >= 15.2-15.3
 · Opera >= 96
 · Safari >= 15.6

 App • Chaining "UI" Webpack config
 App •  WAIT  • Compiling of "UI" in progress...
[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.

[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.

[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.

[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.

[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.

[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.

 App •  DONE  • "UI" compiled with errors • 18291ms

 App •  ERROR  •  UI  Reported by ESLint:
[eslint] EACCES: permission denied, mkdir '/code/node_modules/.cache/eslint-webpack-plugin'
You may use special comments to disable some warnings:
 · // eslint-disable-next-line to ignore the next line.
 · /* eslint-disable */ to ignore all warnings in a file.

 App •  COMPILATION FAILED  • Please check the log above for details.
`
and I checked the albs-frontend bind mounts. Found the path /home/albs/albs/node_modules exists, but there is something wrong with the permission.

![image](https://github.com/AlmaLinux/build-system/assets/32541118/6c4c9606-3fa0-4d98-a7cc-782af8f971ac)

Finally with the help of people in AlmaLinux mattermost I  fixed it by running `chmod -R albs:albs /home/albs/albs/node_modules && cd /home/albs/albs/albs-web-server/ && docker compose -p albs up -d --build --force-recreate frontend`

**Comment by metalefty** [comment]
@m10k This seems an issue you encountered.

**Comment by zklevsha** [comment]
https://github.com/AlmaLinux/albs-frontend/pull/392
https://github.com/AlmaLinux/albs-deploy/pull/6
