### ISSUE TITLE
Add login support for accounts.almalinux.org

### ISSUE THREAD

**Issue by jonathanspw** [AlmaLinux/build-system#138]
We need to implement login support for using accounts.almalinux.org as the authentication source and remove GitHub.

This is to get the logins consistent across our infrastructure and prevent users from having to use commercial 3rd parties for logins.

Ideally we do this with oauth but it could also be LDAP/SAML.

**Comment by javihernandez** [comment]
For the record, after a quick chat today we decided that we won't remove Github for now, we'll just add another option to log into ALBS.

**Comment by jonathanspw** [comment]
Seems perfectly reasonable for now.
