### ISSUE TITLE
SBOM: Incorrect hashes on packages

### ISSUE THREAD

**Issue by xsub** [AlmaLinux/build-system#16]
Hello, I am getting a warning on “Dependency Graph being incomplete” when inspecting SBOM with `alma_sbom.py` for build for kernel source (noarch) package (`kernel-5.14.0-162.12.1.el9_1.alma`):

`env) [a_user@localhost alma-sbom]$ python3.9 alma_sbom.py --output-file=/tmp/kernel-sbom-inspect-by-build-hash.json --file-format cyclonedx-json --build-id 5657
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash adb4b616c2a57bd065fdea79a5b0b064c887d2f752177890d0f5b107d7f88594
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash adb4b616c2a57bd065fdea79a5b0b064c887d2f752177890d0f5b107d7f88594
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash adb4b616c2a57bd065fdea79a5b0b064c887d2f752177890d0f5b107d7f88594
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash ed061fab17b8f269d5fd421a14d0ec81ce5dc357a3ebffe33b5bd2a75e9dd704
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash adb4b616c2a57bd065fdea79a5b0b064c887d2f752177890d0f5b107d7f88594
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash adb4b616c2a57bd065fdea79a5b0b064c887d2f752177890d0f5b107d7f88594
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash ed061fab17b8f269d5fd421a14d0ec81ce5dc357a3ebffe33b5bd2a75e9dd704
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash adb4b616c2a57bd065fdea79a5b0b064c887d2f752177890d0f5b107d7f88594
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash adb4b616c2a57bd065fdea79a5b0b064c887d2f752177890d0f5b107d7f88594
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash ed061fab17b8f269d5fd421a14d0ec81ce5dc357a3ebffe33b5bd2a75e9dd704
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash adb4b616c2a57bd065fdea79a5b0b064c887d2f752177890d0f5b107d7f88594
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash adb4b616c2a57bd065fdea79a5b0b064c887d2f752177890d0f5b107d7f88594
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash ed061fab17b8f269d5fd421a14d0ec81ce5dc357a3ebffe33b5bd2a75e9dd704
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash adb4b616c2a57bd065fdea79a5b0b064c887d2f752177890d0f5b107d7f88594
INFO:root:/usr/bin/cas authenticate --signerID cloud-infra@almalinux.org --output json --hash adb4b616c2a57bd065fdea79a5b0b064c887d2f752177890d0f5b107d7f88594
/home/a_user/env/lib64/python3.9/site-packages/cyclonedx_python_lib-2.7.1-py3.9.egg/cyclonedx/model/bom.py:401: UserWarning: The Component this BOM is describing (PURL=None) has no defined dependencies which means the Dependency Graph is incomplete - you should add direct dependencies to this Component to complete the Dependency Graph data.
  warnings.warn(
INFO:root:Wrote generated SBOM to /tmp/kernel-sbom-inspect-by-build-hash.json
(env) [a_user@localhost alma-sbom]$`

Link to the build: https://build.almalinux.org/build/5657 .

**Comment by xsub** [comment]
It also happens for other builds.

E.g.:

Build 5157 & Anaconda (rpm-build-hash: 70fcf0c5fde092d0e65eeb790313c2b7985c77383fefa04261c03541be0a5bf0) .

**Comment by javihernandez** [comment]
@Korulag I believe that we fixed those long time ago, isn't it?

**Comment by Korulag** [comment]
This one definitely looks fixed, @xsub could you please check it for yourself?
