### ISSUE TITLE
Improve public errata parser

### ISSUE THREAD

**Issue by maccelf** [AlmaLinux/build-system#164]
Improve [public errata parser](https://github.com/AlmaLinux/public-errata-parser)

AC:
- Parser should parse [errata page](https://access.redhat.com/errata-search/)
- Parser should communicate with web server (create an endpoint to update records)
- Parser should update records in Build system DB

**Comment by javihernandez** [comment]
We can consider this issue as resolved as @isudak's [work on public-errata-parser](https://github.com/AlmaLinux/public-errata-parser/pull/1) is done
