### ISSUE TITLE
Disable build SRPM if we already have built SRPM

### ISSUE THREAD

**Issue by forbiddenpotato** [AlmaLinux/build-system#19]
We recently noticed, that ALBS builds SRPM even if it already built SRPM from a first build task in line.
It wastes time and resources for doing useless job.

Acceptance Criteria:
* If SRPM is built in any build-task insude current build, skip building in current build-task.

**Comment by metalefty** [comment]
I think this is a good first issue for me to work on. It will take some time to look around and understand the current code.

**Comment by anfimovdm** [comment]
@metalefty here is a [repo](https://github.com/AlmaLinux/albs-node) where you need to make changes

**Comment by metalefty** [comment]
I think I found the cause.

Check for `is_srpm_required()` is done here:
https://github.com/AlmaLinux/albs-node/blob/d181306875472ff5843d5b6f16f786a656aa3107/build_node/builders/base_rpm_builder.py#L108

But rebuild is always called indirectly after the check, inside `build_packages()`.
https://github.com/AlmaLinux/albs-node/blob/d181306875472ff5843d5b6f16f786a656aa3107/build_node/builders/base_rpm_builder.py#L148
https://github.com/AlmaLinux/albs-node/blob/d181306875472ff5843d5b6f16f786a656aa3107/build_node/builders/base_rpm_builder.py#L251-L254

When we already have built SRPM, that the current code appears to unpack SRPM and rebuild SRPM from the unpacked sources, then build RPM from the SRPM. What a waste!

**Comment by metalefty** [comment]
I have raised draft PR: https://github.com/AlmaLinux/albs-node/pull/57

**Comment by Korulag** [comment]
@metalefty could you please adjust the code in a way that it will not send SRPM if it's not the first arch to build (when the SRPM was downloaded)? And adjust logic of saving artifacts on the web server to account for the case that SRPM may not be in list of the artifacts. Thanks in advance!

**Comment by metalefty** [comment]
This replace the previous pull request: https://github.com/AlmaLinux/albs-node/pull/59

**Comment by anfimovdm** [comment]
https://github.com/AlmaLinux/albs-web-server/pull/607
https://github.com/AlmaLinux/albs-node/pull/63
