### ISSUE TITLE
Migrate metadata uploader to new pulp

### ISSUE THREAD

**Issue by javihernandez** [AlmaLinux/build-system#192]
While fixing tests on https://github.com/AlmaLinux/albs-web-server/pull/726, I stumbled upon the `upload/upload_repometadata` endpoint. This endpoint allows to upload both `modules.yaml` and `comps.xml` files into repositories. `comps.xml` update is fine as it's still an artifact that needs to be uploaded to pulp, but things are different now with new pulp, where modules aren't artifacts anymore.
Bringing this functionality to the new approach around modules is not trivial, as we might need to be very careful when updating things in pulp side and albs db.

The processing of updating modules could look like the following:
1. Get repo href and module content 
2. Get
  2.1 modulemds and modulemd-defaults in current repo
  2.2 modulemds and modulemd-defaults in module content
3. Add/Remove modulemds into pulp (via pulp_client.modify_repo)
  3.1 If new module in repo - add it
  3.2 If already existing - update it
  3.3 Packages will change, so we need to add/remove manually too
4. Add/Remove modulemd-defaults into pulp
  4.1) Generate digest and save with new content (mostly snippet)
5. Make the appropriate updates in albs db 
6. Re-publicate pulp repos

**Comment by Korulag** [comment]
1. modulemd-defaults should be checked first, then added via https://docs.pulpproject.org/pulp_rpm/restapi.html#tag/Content:-Modulemd_Defaults/operation/content_rpm_modulemd_defaults_create. If the entity already exists, see if it needs to be updated - use direct database connection;
2. Updateinfo should be updated using direct database connection;
3. The rest is as it was, other APIs didn't change.
