### ISSUE TITLE
Fix 401 when click to the Advisory info

### ISSUE THREAD

**Issue by maccelf** [AlmaLinux/build-system#199]
When you try to click to Advisory info you get 401
![Screenshot from 2024-02-20 22-06-13](https://github.com/AlmaLinux/build-system/assets/48645931/d7bf967a-226d-4cce-be5b-9671f5014162)
![Screenshot from 2024-02-20 22-06-08](https://github.com/AlmaLinux/build-system/assets/48645931/447c9687-7e0f-493f-94fc-cbeb17840b6e)
![Screenshot from 2024-02-20 22-06-19](https://github.com/AlmaLinux/build-system/assets/48645931/0aec4bbc-d463-4f85-98bb-48801799500c)

**Comment by javihernandez** [comment]
Hey @maccelf, I'm not experiencing this on production 
![image](https://github.com/AlmaLinux/build-system/assets/821790/f4f208cb-4a4f-4a5e-a4eb-6169098932d9)

**Comment by javihernandez** [comment]
Ok, I tried in a clean browser session and I'm getting exactly the same error as you @maccelf - so we might have another problem. Maybe, we're not fully cleaning the session when logging out. Can you please check that too? It's okay if we need another ticket for that one.
