### ISSUE TITLE
Research CI tools for AlmaLinux Build System

### ISSUE THREAD

**Issue by forbiddenpotato** [AlmaLinux/build-system#201]

**Comment by isudak** [comment]
- [ ] Set up tests for the AlmaLinux/albs-sign-file repo

**Comment by isudak** [comment]
Regarding the code coverage. If we'd like to have some sort of statistics on coverage over time or more deep analytics then usage of only `pytest` reports is not enough. We might take a look at services like [codecov.io](https://about.codecov.io/) and their [Codecov](https://github.com/marketplace/actions/codecov) GitHub action. They are free for open source projects.

**Comment by isudak** [comment]
During the work on [Set up a GitHub workflow for checking the PR title/description ...](https://github.com/AlmaLinux/build-system/issues/214) I stumbled upon an `$GITHUB_TOKEN` permission issue. The workflow triggered on `pull_request` was not able to post a comment on the PR page. Digging into it I found this excellent article on GitHub Action security [Keeping your GitHub Actions and workflows secure ](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/).

So, we need to split the Preflight workflow into 2 parts:

1. Running the tests in an unprivileged environment using the `pull_request` event and upload `pytest` reports using [upload-artifact](https://github.com/actions/upload-artifact)
2. Posting a PR comment in another workflow triggered by the `workflow_run` event after the first step is completed. It should download uploaded artifacts on the first step using [download-artifact](https://github.com/actions/download-artifact). This workflow runs with full write access and may port comments.

**Comment by isudak** [comment]
[albs-sign-node](https://github.com/AlmaLinux/albs-sign-node)
- [ ] Set up the test configuration
- [ ] Set up test workflows and RP/commit message checking workflows
- [ ] Increase test coverage among ALBS repos
- [ ] Set up a workflow generating a test coverage badge

**Comment by isudak** [comment]
[albs-node](https://github.com/AlmaLinux/albs-node)
- [ ] Set up the test configuration
- [ ] Set up test workflows and RP/commit message checking workflows
- [ ] Set up a workflow generating a test coverage badge
