### ISSUE TITLE
Change build order slightly

### ISSUE THREAD

**Issue by jonathanspw** [AlmaLinux/build-system#212]
When doing parallel builds currently we have to wait on the first build (x86 generally) to finish before the other builds can start, so that they all use the same SRPM.  This creates unnecessary delays which is particularly frustrating when doing builds by hand for testing, etc.

SRPM generation is very fast relative to full builds, so it would make the most sense to have a dedicated step for building the SRPM, then trigger all of the builds at once.  The result should basically be that builds take half as long because you're not waiting on the first build to finish before running the rest, only the SRPM build.

Mentioned this briefly to @javihernandez in Brussels and I think he understands what I'm getting at here.

**Comment by javihernandez** [comment]
Hey @jonathanspw, first, thanks for this suggestion.

We have talked about this and these are our thoughts.

This involves factoring the SRPM build out of the current build process and make it a separate first step, this is:
1. try building the srpm
2. if no srpm can be built - mark build as failed
3. if we got an srpm - keep going with rpm building

It would involve some non-trivial refactoring of our current workflow, but we believe that this won't only be beneficial in building (or failing) speed, but also, it's a good opportunity for us to simplify the current logic around the `srpm_built` checks, that now can be go into a separate `process_srpm` method and `process_rpms` will become simpler.

It would also involve updating the UI to reflect the changes. Right now, we have this:

![image](https://github.com/AlmaLinux/build-system/assets/821790/fae7042c-bded-4085-942e-c2d9239bc8fe)

And when looking at build logs, we get this:

![image](https://github.com/AlmaLinux/build-system/assets/821790/62785a94-58f4-4287-8e15-b186c88de540)

After the changes are made in backend, we'd need to:
* Remove the SRPM build logs from current arch build logs view
* Add a new `src` column alongside the rest of the arches, and upon clicking on it, it'll show the SRPM build logs
