### ISSUE TITLE
noarch packages displays multiple times when creating a release

### ISSUE THREAD

**Issue by forbiddenpotato** [AlmaLinux/build-system#22]
When creating a new release to a copr repo, noarch package is displayed multiple times (as many as “done” arch builds?)

![Image](https://user-images.githubusercontent.com/135831959/244392191-e19a8471-93dd-494e-b479-5fe082460620.png)

![Image](https://user-images.githubusercontent.com/135831959/244392242-61ce469f-a231-4ec8-934c-08cf7febbb21.png)

**Comment by m10k** [comment]
I think it should be enough to filter duplicate packages on the client/browser side. Maybe with a checkbox to un-hide duplicate packages (if there is a usecase for that). What do you think?

**Comment by m10k** [comment]
I just created a PR with a bugfix:
https://github.com/AlmaLinux/albs-web-server/pull/606


### Screenshot without patch

![Image](https://github.com/AlmaLinux/build-system/assets/19570637/bcbcb1a3-4790-4883-a73a-42476e0f798f)

### Screenshot with patch

![Image](https://github.com/AlmaLinux/build-system/assets/19570637/86a70dea-990f-4922-882a-d806c6b21d3f)

**Comment by anfimovdm** [comment]
deployed on the production
