### ISSUE TITLE
Add mechanism of generating community PGP keys

### ISSUE THREAD

**Issue by forbiddenpotato** [AlmaLinux/build-system#24]
AC

1. All keys will be generated on a separate community sign-node
2. Each key shouldn’t be protected by a password, because we can store them securely now. We will harden access to the sign node.
3. Mechanism can generate PGP key
  - For generating a key can be used a scenario file (example of scenario’s template can be found by [link](https://github.com/AlmaLinux/albs-deploy/blob/master/roles/dev_deploy/templates/gpg-key-scenario.j2))
  - Command for generating PGP key with using scenario file `gpg --batch --gen-key <output db> <path to scenario>`

**Comment by soksanichenko** [comment]
https://github.com/AlmaLinux/albs-sign-node/pull/12

**Comment by soksanichenko** [comment]
https://github.com/AlmaLinux/albs-web-server/pull/574
