### ISSUE TITLE
Collect requirements/thoughts from the community on building custom products

### ISSUE THREAD

**Issue by javihernandez** [AlmaLinux/build-system#283]
The tentative plan for this is described in the [Building custom products milestone](https://github.com/AlmaLinux/build-system/milestone/1). Some work has been done already but there are still things that we need to make it happen. Feel free to add your thoughts/requirements on this ticket as comments so we can update and/or eventually extend the current plan.

**Comment by jonathanspw** [comment]
I'd like to see https://github.com/AlmaLinux/build-system/issues/212 as a blocker for this.  It will significantly improve user experience/speed.

Will https://github.com/AlmaLinux/build-system/issues/21 be done automatically, or on demand/checkbox?  I'd argue that it should just be automatic.  There's no real reason *not* to do it, and it will just keep thing simpler for the user if it's one less checkbox, or at a least a default-checked box.

We should definitely finish the Alma Account integration and 100% rely on that (and permissions/roles synced with it, etc. but that really only applies to "staff" users) and away from GH.  That should definitely be a blocker for this as we don't want to continue with GH for public use.

**Comment by javihernandez** [comment]
Thanks for your feedback, some answers below

> I'd like to see #212 as a blocker for this. It will significantly improve user experience/speed.

I wouldn't consider it a blocker, but definitely nice to have ASAP /cc @forbiddenpotato @Korulag 

> Will #21 be done automatically, or on demand/checkbox? I'd argue that it should just be automatic. There's no real reason _not_ to do it, and it will just keep thing simpler for the user if it's one less checkbox, or at a least a default-checked box.

This is already implemented, but need to double check that the workflow is currently working

> We should definitely finish the Alma Account integration and 100% rely on that (and permissions/roles synced with it, etc. but that really only applies to "staff" users) and away from GH. That should definitely be a blocker for this as we don't want to continue with GH for public use.

Bear in mind that ALBS has its own RBAC implementation, which I believe is useful in most of the use cases, but, maybe to be considered/discussed.
