### ISSUE TITLE
Wrong artifacts placing in modules

### ISSUE THREAD

**Issue by forbiddenpotato** [AlmaLinux/build-system#30]
In https://build.almalinux.org/build/4512 modules, devel module contains artifacts that not in module filters, also source artifacts are missing in non-devel module.

After discussion, we come to this logic:
- The Main module should have an src.rpm for all the binaries in that module (if ALL binaries got into Devel, then src.rpm goes there);
- There cannot be the same artifacts in the Main module and the Devel module;
- Artifacts that are in the filter sections do not go to the Main module but go to the Devel module;
- src.rpm for the excluded arch are going to the Devel module;
- For multilib modules, artifacts with i686 arch go to x86_64 arch.
  - Multilib artifacts are going into the Main module if they are marked like this: [multilib: [x86_64]](https://git.almalinux.org/modules/llvm-toolset/src/commit/8b28dca34c7e34969f11005f3c9af9b625fa4f5e/SOURCES/modulemd.src.txt#L47) in the components section of module yaml (ruby, llvm-toolset);
  - Other multilib artifacts are going into the Devel module (mariadb, virt, subversion).

Now we need to put packages according to that logic and make it so in future they'll do it automatically.

**Comment by javihernandez** [comment]
So far, all I can say is that, nowadays, we're placing modules the right way. I've took over @maccelf's https://github.com/AlmaLinux/albs-web-server/pull/478 PR, updated with current master and fixed a couple of things here and there, BUT, the tests aren't passing and need to be finalized. I'll get back to this one when I have time for it.

**Comment by maccelf** [comment]
For some reason, `SLOF-0:20210217-1.module_el8.6.0+2880+7d9e3703.src` is missing in the `virt-devel`. After discussing it with Andrew it turned out that this was a bug and we should put src for excluded packages to the devel module.
