### ISSUE TITLE
Broken modular metadata

### ISSUE THREAD

**Issue by javihernandez** [AlmaLinux/build-system#310]
[https://build.almalinux.org/build/13344](https://build.almalinux.org/build/13344)
This build will be an example
As you see in x86_64 modular metadata, the same noarch and src packages are mentioned twice
```
  - python39-six-0:1.15.0-3.module_el8.6.0+2780+a40f65e1.noarch
  - python39-six-0:1.15.0-3.module_el8.6.0+3248+c431e88c.noarch
  - python-pluggy-0:0.13.1-3.module_el8.6.0+2780+a40f65e1.src
  - python-pluggy-0:0.13.1-3.module_el8.6.0+3248+c431e88c.src
```
It happens because s390x packages were built later than other architectures.
On x86_64 packages, should be mentioned packages only from the latest x86_64 modular metadata.

**Comment by Korulag** [comment]
It can be also a thing that we did not deleted artifacts from rebuilt project in the first place. We need to ensure that we delete all artifacts for those projects we are rebuilding
