### ISSUE TITLE
Enable deployment under a proxy environment

### ISSUE THREAD

**Issue by pastalian** [AlmaLinux/build-system#312]
While most components respect the environment variables such as http_proxy, pulp does not, so the current build system does not work well in a proxy environment.

https://pulpproject.org/pulp_rpm/restapi/#tag/Remotes:-Rpm/operation/remotes_rpm_rpm_create
Pulp requires proxy settings to be specified for each rpm remote.

**Comment by pastalian** [comment]
I guess I can't reopen this issue even though I opened it.

Anyway, I noticed alts need some adjustments as well. (don't have time for it yet)

https://github.com/AlmaLinux/alts/blob/79654d57a5d78f35bdc63861d0e52fba84b434d7/resources/roles/preparation/tasks/main.yml#L25-L34
→ doesn't work under proxy

https://github.com/AlmaLinux/alts/blob/79654d57a5d78f35bdc63861d0e52fba84b434d7/resources/roles/preparation/tasks/rhel.yml#L55-L61
→ ignores symlink to dnf.conf. needs `follow: true`

https://github.com/AlmaLinux/alts/blob/79654d57a5d78f35bdc63861d0e52fba84b434d7/resources/roles/preparation/tasks/rhel.yml#L134-L142
→ needs no_proxy equivalent most likely

**Comment by javihernandez** [comment]
> I guess I can't reopen this issue even though I opened it.
> 
> Anyway, I noticed alts need some adjustments as well. (don't have time for it yet)

You can create a new issue to address stuff on alts :)
