### ISSUE TITLE
Rebuild srpm if all architectures are failed

### ISSUE THREAD

**Issue by eabdullin1** [AlmaLinux/build-system#323]
We need to rebuild srpm if all architectures are failed
In this build I tried to rebuild 2 times and srpm was not rebuilt [https://build.almalinux.org/build/15823](https://build.almalinux.org/build/15823)

**Comment by Korulag** [comment]
When we proceed through the build and we have all build projects failed then we need to unset `srpm_url` on build tasks for item that have fully failed
