### ISSUE TITLE
Deleting a product while build is in progress

### ISSUE THREAD

**Issue by forbiddenpotato** [AlmaLinux/build-system#33]
I created a product, created a new build for this product. Then I deleted a product while the build is in the process and stopped the build after product deletion. 

Expected behavior: an inability with warning that you can delete the product while it has building packages in progress. Would be nice to have a checking that it won’t be repeated.

The behavior I got: the product was just normally deleted. The build was still building into “nowhere”. I stopped the build, but it’s not possible to delete it. I created a new product with alike name and some editions I needed, but it’s currently impossible to work with it.

The build it happened to: https://build.almalinux.org/build/5959

**Comment by anfimovdm** [comment]
https://github.com/AlmaLinux/albs-frontend/pull/365
https://github.com/AlmaLinux/albs-web-server/pull/579
