### ISSUE TITLE
Project is being added as "undefined"

### ISSUE THREAD

**Issue by forbiddenpotato** [AlmaLinux/build-system#34]
When creating a build, a project might be added as “undefined” and a user has to add is again but carefully.
Steps to reproduce:
1. Create build and choose arch/product (that was AlmaLinux 9 for all arches)
2. Add project → and switch to the “Src-rpm URL”
3. Print there anything and switch to [git.almalinux.org](http://git.almalinux.org/) option
4. Find the project you really need, choose the branch
5. Click “Add”
6. The project is added as undefined. A user now has to delete this and add the project again without any “mistakes”

**Comment by maccelf** [comment]
https://github.com/AlmaLinux/albs-frontend/pull/363
