### ISSUE TITLE
Add AlmaLinux-9 platform to products

### ISSUE THREAD

**Issue by forbiddenpotato** [AlmaLinux/build-system#358]
Can you please add AlmaLinux-9 platform to 
[https://build.almalinux.org/product/117](https://build.almalinux.org/product/117)
[https://build.almalinux.org/product/50](https://build.almalinux.org/product/50)
And create all repositories

**Comment by maccelf** [comment]
Added AlmaLinux-9 platform to
https://build.almalinux.org/product/117
https://build.almalinux.org/product/50

@eabdullin1 Could you please check ?

**Comment by eabdullin1** [comment]
Thank you. The repositories exist
