### ISSUE TITLE
Custom product access management

### ISSUE THREAD

**Issue by forbiddenpotato** [AlmaLinux/build-system#37]
AC:
- User with sufficient access role can assign roles for this product to another users of the Build System
- Available roles:
  - Owner (can change product metadata and assign/remove additional owners and releasers to this product)
  - Administrator (can assign/remove releasers to this product)
  - Releaser (can sign and release to this product)
- Owner always administrator and releaser
- At least one Owner required (can't remove the last one) 
- User can have many roles

**Comment by javihernandez** [comment]
> * User with sufficient access role can assign roles for this product to another users of the Build System
> * Available roles:
>   
>   * Owner (can change product metadata and assign/remove additional owners and releasers to this product)
>   * Administrator (can assign/remove releasers to this product)
>   * Releaser (can sign and release to this product)

All this is already possible

![image](https://github.com/AlmaLinux/build-system/assets/821790/61fe8254-4a44-4f9d-a7b6-46bb4abdcbea)
![image](https://github.com/AlmaLinux/build-system/assets/821790/8beebb87-6d77-4841-9b56-8993828f24d4)

Other items in AC are still required, but not urgent in my opinion.
