### ISSUE TITLE
Group errata packages by architecture in errata pages

### ISSUE THREAD

**Issue by javihernandez** [AlmaLinux/build-system#39]
AlmaLinux OS erratas are available at https://errata.almalinux.org.
Errata pages already deliver the relevant information in a very efficient way, so we can check things at a glance. However, when willing to check updated packages, if there are many packages listed, searching for a specific package can be a bit difficult. i.e.: Check [this one](https://errata.almalinux.org/8/ALSA-2021-4222.html)

![image](https://github.com/AlmaLinux/build-system/assets/821790/bde08fd3-1603-45b7-80d9-1ab40ff3556a)

As you can see, it looks messy. Still, you can `Ctrl+f` on the browser and search for whatever you're looking for, but I think that grouping the packages by architecture, could be a simple thing that we can do to improve its current UX. Bonus points if we can sort the packages when displaying them, and this order is consistent in all architectures.

**Comment by metalefty** [comment]
I can take this.

**Comment by metalefty** [comment]
Example: sorted by arch

![image](https://github.com/AlmaLinux/build-system/assets/941609/ae4716f6-9a7e-4a03-b42a-9ed32749c8c5)

**Comment by metalefty** [comment]
Today I was working on our internal stuff so there's no progress to report. I'm thinking of sort-by-arch for package lists in errata. I will implement it if this is fine.

**Comment by metalefty** [comment]
Raised PR: https://github.com/AlmaLinux/albs-web-server/pull/625

> Bonus points if we can sort the packages when displaying them, and this order is consistent in all architectures.

Bonus points tasks depends on if to display checksums or not. I need to consider better UI/UX with checksums. See also: https://github.com/AlmaLinux/build-system/issues/98
