### ISSUE TITLE
Make errata_index more dense

### ISSUE THREAD

**Issue by pastalian** [AlmaLinux/build-system#407]
After https://github.com/AlmaLinux/errata_index/pull/8 was deployed, when "records per page" is small relative to the screen size, each row takes up too much space.

I think it should look more like 2 or 3. Any other ideas?
1. current
![24-12-07_173946](https://github.com/user-attachments/assets/a263db28-b931-49ec-a8a8-896e1765d55e)

2. previous
![24-12-07_174137](https://github.com/user-attachments/assets/cecf0752-3bed-4d44-b2d2-cd98d1c7b3f8)

3. another option
![24-12-07_173937](https://github.com/user-attachments/assets/4aba91bf-eda5-4eb6-8ac8-32fb476e3083)

**Comment by javihernandez** [comment]
Not a strong opinion, but I'd go for the 2nd one.
Also, have you tried on other browsers/displays? It might render differently when applying such changes, or at least, that's what we experienced the last time we played around with styling.
