### ISSUE TITLE
Create a service to parse RHEL public errata data

### ISSUE THREAD

**Issue by Korulag** [AlmaLinux/build-system#51]
We need to have a service which will parse RHEL public Errata site and retrieve the information about the bugfixes/enhancements/security advisories from there.
- The parsed data is stored in database;
- The data do not conflict with the ones parsed from OVAL streams (and vice versa);
- Ability to define an exclude list for the package;
- Create Github task with the information on the advisory.

**Comment by xsub** [comment]
Notified @andrewlukoshko, he promised to look at it. 

@Korulag, @forbiddenpotato: please consider tagging him next time we need his review. Thanks.

**Comment by maccelf** [comment]
We already had all the functionality in our oval-cacher
