### ISSUE TITLE
Integrate Errata parser with Github to create issues there

### ISSUE THREAD

**Issue by Korulag** [AlmaLinux/build-system#52]
We need an integration between Errata parsing service and our AlmaLinux Github board in order to receive new issues automatically if something was found in security bulletins.
- Explore the already written options to communicate with Github;
- Create a separate repository which will have all the necessary code to support our workflow.

**Comment by maccelf** [comment]
We need to write Errata parser first

**Comment by maccelf** [comment]
Blocked by https://github.com/AlmaLinux/build-system/issues/164

**Comment by javihernandez** [comment]
Right now we're creating issues in https://github.com/orgs/AlmaLinux/projects/4 when new advisories are added into web_server.  Do we still need this? I'd say we don't

**Comment by maccelf** [comment]
Yes, I agree. We can close this issue I suppose

**Comment by javihernandez** [comment]
Closing. Re open if needed
