### ISSUE TITLE
Build package after the patches are applied

### ISSUE THREAD

**Issue by Korulag** [AlmaLinux/build-system#69]
- If we applied patch(-es) faster than RedHat - add `.alma.1` suffix to the release;
- If RedHat delivered the fix faster - use their version, without `.alma.$` suffix;
- Notify in Github that build is started and provide a link to the build.

**Comment by maccelf** [comment]
Blocked by https://github.com/AlmaLinux/build-system/issues/135

**Comment by maccelf** [comment]
Blocked by #149
