### ISSUE TITLE
Add ability to cancel testing

### ISSUE THREAD

**Issue by anfimovdm** [AlmaLinux/build-system#81]
It would be great if users could cancel testing manually. I'm not talking about stopping already running tests (but maybe we would want to implement that too), but now it will be enough to cancel testing until the build is finished.

**Comment by metalefty** [comment]
Not focusing to stop already running tests here, what does 'cancel testing' mean?

I would like to clarify the criteria.

**Comment by forbiddenpotato** [comment]
we want to clear test queue from all test tasks that are not yet started

**Comment by javihernandez** [comment]
I created the following PRs to bring this new functionality:
* https://github.com/AlmaLinux/albs-frontend/pull/407
* https://github.com/AlmaLinux/alts/pull/76
* https://github.com/AlmaLinux/albs-web-server/pull/709

How it works:
1. Users can cancel test tasks of a particular build from UI
2. web_server send cancelled task_ids to ALTS
3. ALTS:
  3.1 Revokes immediately those that aren't already running
  3.2 Tries to gracefully terminate the already running ones
  3.3 Report test results back to web_server
