### ISSUE TITLE
ALBS can't build multiplatform builds because it puts sRPM to a wrong repo

### ISSUE THREAD

**Issue by soksanichenko** [AlmaLinux/build-system#87]
https://build.almalinux.org/build/7035

**Comment by forbiddenpotato** [comment]
Currently, when you add more than one platform into build, ALBS can't handle multilibs and noarch.
Need to process those only for platform that is being processed by build task.

**Comment by forbiddenpotato** [comment]
AC:
+ provisioning for multiarch build nodes

**Comment by soksanichenko** [comment]
No we can't set up build nodes for another arch than x86_64 using qemu-user-static, because `mock` doesn't work through translation.

**Comment by soksanichenko** [comment]
What I did:

- Select only right rpm repositories by a platform while processing a build task artifacts
- Update built_srpm_url only for the build tasks of one platform
- Select and put noarch packages only among the build tasks of one platform
- Create raw_refs per each existing platform, not only first platform from the list
