### ISSUE TITLE
AlmaLinux Build System Licensing Question and Copyright Practice

### ISSUE THREAD

**Issue by xsub** [AlmaLinux/build-system#92]
**Description:**
We are seeking clarification on the licensing practices for the AlmaLinux Build System. 
Specifically, we have three questions that we would like to address:

**SPDX SBOM License Choice:** The Build Team has tentatively selected the Creative Commons Zero v1.0 Universal (CC0) license for the Software Package Data Exchange (SPDX) Software Bill of Materials (SBOMs). We would like to confirm if this licensing choice aligns with the foundation's stance.

**Licensing for New Code:** We would like to know what license should be used when creating new code for the build system. Is there a specific license that the foundation recommends for code created for the build system?

**GPL3 Licensed Code in Build System:** We have observed that some code in the build system is licensed under the GNU General Public License v3 (GPL3). In order to ensure uniformity in licensing, we request clear direction from the foundation on permissible licenses for code in the build system. Additionally, we would like to know the correct format for license headers in source files, particularly with regard to the Copyright (C) 20xx Author / Foundation Name section.
We would appreciate prompt feedback from the team leads on these questions so that we can proceed with the development of the build system in alignment with the foundation's licensing practices.

**Additional Information:**
Based on the suggestion from @javihernandez, we would like to share an approach to handling copyrights in source code. In previous organizations, the practice was to mention whoever sponsors the developer's time working on the project in the copyright notice. We believe this approach could be useful in our case as well.

Moreover, @javihernandez identified that some source code files in the build system lack license and copyright information. We believe it would be beneficial to establish a policy document addressing the inclusion of license and copyright information in source code files. To this end, we recommend creating a separate GitHub issue to facilitate the development of this policy.

Thank you!

**Comment by bennyvasquez** [comment]
Working on getting these answers together for you! Hoping to have ti all for you today.

**Comment by bennyvasquez** [comment]
hey all! We've added the following guidance to the licensing policy [on the website](https://almalinux.org/p/the-almalinux-os-licensing-policy/) which I hope helps to answer all of these questions. If there's anything lingering after taking all of the updates into considering, let me know!

**Comment by bennyvasquez** [comment]
This has been updated: https://almalinux.org/p/the-almalinux-os-licensing-policy/ I shared in mattermost yesterday too.

**Comment by xsub** [comment]
@andrewlukoshko @forbiddenpotato @javihernandez is this version satisfying our requests and addressing all concerns?

**Comment by forbiddenpotato** [comment]
Looks good to me. Mentioning Fedora Project in "Explicitly Licensed Contributions" caught my eye, but I believe it's because AlmaLinux.org Content don't overlap 100% with it.
@andrewlukoshko what do you think?

**Comment by bennyvasquez** [comment]
Looks like it's leftover from the duplication of the CentOS license, and it looks like there's a formatting error on that page, too that I've submitted a PR to fix. This is the page that the Centos license links to: https://docs.fedoraproject.org/en-US/legal/license-approval/
