### ISSUE TITLE
errata: checksum is empty

### ISSUE THREAD

**Issue by metalefty** [AlmaLinux/build-system#98]
See: https://errata.almalinux.org/9/ALSA-2023-4708.html

![image](https://github.com/AlmaLinux/build-system/assets/941609/32bf7ae7-c3ad-43f7-9986-d683f0a85583)

**Comment by metalefty** [comment]
First of all, I would like to confirm if checksums are intentionally hidden or not.

**Comment by metalefty** [comment]
This is my errata page candidate, still sucks.

![image](https://github.com/AlmaLinux/build-system/assets/941609/cca84ae5-fffa-45b9-a343-76aa79076833)

**Comment by metalefty** [comment]
BTW, I guess these `div`s are unnecesary because tabs are not used.

```diff
diff --git a/alws/utils/templates/errata_alma_page.j2 b/alws/utils/templates/errata_alma_page.j2
index 80e982f..ce20b61 100644
--- a/alws/utils/templates/errata_alma_page.j2
+++ b/alws/utils/templates/errata_alma_page.j2
@@ -30,9 +30,6 @@
 </div>


-<div class="tabs-content" data-tabs-content="images-tabs">
-
-    <div class="tabs-panel row is-active">
         <div class="row card">
             <div class="medium-12 columns card-header">
                 <h5>[{{ errata['updateinfo_id'] }}] {{ errata['title'] }}</h5>
@@ -120,7 +117,5 @@
             </div>
             </div>
         </div>
-    </div>
-</div>
 </body>
 </html>
```

**Comment by forbiddenpotato** [comment]
Idea: It is the end of the page, so we can take full width of white space.
![image](https://github.com/AlmaLinux/build-system/assets/135831959/297d95c0-85fb-4449-b72c-5f3b56070428)

**Comment by metalefty** [comment]
Looks better.

**Comment by metalefty** [comment]
Implemented sorting with jQuery tablesort plugin. Which do you like? 

### Tablesort's default theme

This is compact, but the style is not harmonious with other parts. 

![image](https://github.com/AlmaLinux/build-system/assets/941609/52d8202e-b245-490f-afb0-63b3276002c9)


### Tablesort's material design theme

This just adds a sorting feature, the style is almost same with the original table but there's horizontal scrolling.

![image](https://github.com/AlmaLinux/build-system/assets/941609/58c9dd55-5506-4640-976c-ca9a321051c4)

**Comment by forbiddenpotato** [comment]
Let's try popular vote. There are two variants shown in previous comment, add your emote to it if you think we should use:
:rocket: - first one, where everything fits, but small
:tada: - second one, where we have horizontal scroll 
:eyes: - neither, you have another idea you will present in comment

**Comment by metalefty** [comment]
Either way, I can switch styles by changing CSS to apply. It's easy to switch.

**Comment by javihernandez** [comment]
> Let's try popular vote. There are two variants shown in previous comment, add your emote to it if you think we should use:
> 🚀 - first one, where everything fits, but small
> 🎉 - second one, where we have horizontal scroll
> 👀 - neither, you have another idea you will present in comment

personally I don't like horizontal scrolling :)

**Comment by metalefty** [comment]
PR for errata_index: https://github.com/AlmaLinux/errata_index/pull/4

**Comment by forbiddenpotato** [comment]
https://github.com/AlmaLinux/albs-web-server/pull/632

**Comment by metalefty** [comment]
All PRs are merged and have been deployed.
